# action.yml
name: 'App Version Actions'
description: 'Version operations'
inputs:
  given_file_name:  # id of input
    description: 'Name of the version file'
    required: true
    default: 'version'
outputs:
  app_version: # id of output
    description: 'Version from given file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.given_file_name }}